version: "3.1"
services:
    www:
        image: vicsoft01/ubuntu-apache
        ports:
            - "8050:80"
        volumes:
            - /home/nousers/web/backup/public/Backup-RegaloNatural:/var/www/html/
        links:
            - db:db
        networks:
            - default
    db:
        image: mysql:5.7
        ports:
            - "33060:3306"
        command: --default-authentication-plugin=mysql_native_password
        #command: mysql -uroot -pvmsn2004 < creacion.sql
        environment:
            #MYSQL_DATABASE: myDb
            MYSQL_USER: victor
            MYSQL_PASSWORD: vmsn2004
            MYSQL_ROOT_PASSWORD: vmsn2004
        volumes:
            - /home/nousers/web/backup/mysql:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: victor
            MYSQL_PASSWORD: vmsn2004
            MYSQL_ROOT_PASSWORD: vmsn2004
        networks:
            - default
